// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `angular-cli.json`.
// `.env.ts` is generated by the `npm run env` command
// import env from './.env';

const production = '<%= PRODUCTION %>';
const serverUrl = '<%= SERVER_URL || "https://api.neworleansexperience.com/" %>';
const errorTrackingEnv = '<%= ERROR_TRACKING_ENV || "dev" %>';
const googleMapsKey = '<%= GOOGLE_MAPS_KEY || "" %>';
const applicationVersion = '<%= APPLICATION_VERSION || "" %>';
const domain = '<%= DOMAIN || "localhost" %>';

export const environment = {
  production: production,
  serverUrl: serverUrl,
  errorTrackingEnv: errorTrackingEnv,
  applicationVersion: applicationVersion,
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ],
  googleMapsKey: googleMapsKey,
  domain: domain
};
